### ISSUE TITLE
Does not work with Qlik sense Jun 17 release

### ISSUE THREAD

**Issue by prasadmundewadi** [bardess/app-on-demand#2]
Hi
I could install the extension on our qlik sense server but when i try to use it on a sheet it says 'Invalid Vizualization'
Is this not compatible with Jun 17 release?

**Comment by jamesfleming** [comment]
Has not been tested yet but we will look into it and see if there is a patch.

Also keep in mind that Qlik Sense now has On Demand App Generation (ODAG) in the June 2017 release. This would be the preferred method just because its a native and supported.

**Comment by prasadmundewadi** [comment]
Where exactly can I find On Demand App Generation (ODAG) in Qlik sense Jun release? It’s not under vizualizations.

[cid:image002.jpg@01D3174B.7A997620]

**Comment by jamesfleming** [comment]
Sure you have to enable it on the QMC in this menu:

![image](https://user-images.githubusercontent.com/4334863/29420512-239c9742-8340-11e7-9851-839db43b7c16.png)

![image](https://user-images.githubusercontent.com/4334863/29420528-33c624ee-8340-11e7-8980-42de0df7eb35.png)

Then it comes up in edit mode:

![image](https://user-images.githubusercontent.com/4334863/29420569-55b89898-8340-11e7-8933-2d98ad78d5af.png)

![image](https://user-images.githubusercontent.com/4334863/29420582-602c1c64-8340-11e7-8007-e2cff9e73e5b.png)
